---
- name: "system :: run manjaro"
  ansible.builtin.import_tasks: os/manjaro.yml
  when: ansible_os_family == "Archlinux"

- name: "system :: run ubuntu"
  ansible.builtin.import_tasks: os/ubuntu.yml
  when: ansible_os_family == "Debian"
